FAILURE_THRESHOLD_KEY = 0
COUNT_THRESHOLD_KEY = 1
ANY_THRESHOLD_KEY = 2
GLOBAL_ANY_THRESHOLD_KEY = 3
GLOBAL_FAIL_THRESHOLD_KEY = 4
INTERVAL_KEY = 200
ENFORCE_TCP_KEY = 201

GLOBAL_IP = 0

# metrics
REQUEST_SIZE_KEY = 0
RESPONSE_SIZE_KEY = 1
RESPONSE_TIME_KEY = 2

DDOS_INTERFACE = "LMP_DDOS_INTERFACE"