apiVersion: v1
kind: Pod
metadata:
  name: grpcclient
  namespace: wyw
spec:
  containers:
    - image: wyuei/grpc_client
      name: grpcclient
      command: ["/go/src/grpc_client/main"]
      args: ["--address=10.0.0.199:50051"]