// Code generated by bpf2go; DO NOT EDIT.

package sockops

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpf_sockopsAddr2Tuple struct {
	Ip4  uint32
	Port uint32
}

type bpf_sockopsSocket4Tuple struct {
	Local  bpf_sockopsAddr2Tuple
	Remote bpf_sockopsAddr2Tuple
}

// loadBpf_sockops returns the embedded CollectionSpec for bpf_sockops.
func loadBpf_sockops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_sockopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_sockops: %w", err)
	}

	return spec, err
}

// loadBpf_sockopsObjects loads bpf_sockops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *bpf_sockopsObjects
//     *bpf_sockopsPrograms
//     *bpf_sockopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_sockopsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_sockops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_sockopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_sockopsSpecs struct {
	bpf_sockopsProgramSpecs
	bpf_sockopsMapSpecs
}

// bpf_sockopsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_sockopsProgramSpecs struct {
	BpfSockmap *ebpf.ProgramSpec `ebpf:"bpf_sockmap"`
}

// bpf_sockopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_sockopsMapSpecs struct {
	DebugMap       *ebpf.MapSpec `ebpf:"debug_map"`
	LocalIpMap     *ebpf.MapSpec `ebpf:"local_ip_map"`
	MapActiveEstab *ebpf.MapSpec `ebpf:"map_active_estab"`
	MapProxy       *ebpf.MapSpec `ebpf:"map_proxy"`
	MapRedir       *ebpf.MapSpec `ebpf:"map_redir"`
}

// bpf_sockopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_sockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_sockopsObjects struct {
	bpf_sockopsPrograms
	bpf_sockopsMaps
}

func (o *bpf_sockopsObjects) Close() error {
	return _Bpf_sockopsClose(
		&o.bpf_sockopsPrograms,
		&o.bpf_sockopsMaps,
	)
}

// bpf_sockopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_sockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_sockopsMaps struct {
	DebugMap       *ebpf.Map `ebpf:"debug_map"`
	LocalIpMap     *ebpf.Map `ebpf:"local_ip_map"`
	MapActiveEstab *ebpf.Map `ebpf:"map_active_estab"`
	MapProxy       *ebpf.Map `ebpf:"map_proxy"`
	MapRedir       *ebpf.Map `ebpf:"map_redir"`
}

func (m *bpf_sockopsMaps) Close() error {
	return _Bpf_sockopsClose(
		m.DebugMap,
		m.LocalIpMap,
		m.MapActiveEstab,
		m.MapProxy,
		m.MapRedir,
	)
}

// bpf_sockopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_sockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_sockopsPrograms struct {
	BpfSockmap *ebpf.Program `ebpf:"bpf_sockmap"`
}

func (p *bpf_sockopsPrograms) Close() error {
	return _Bpf_sockopsClose(
		p.BpfSockmap,
	)
}

func _Bpf_sockopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed bpf_sockops_bpf.o
var _Bpf_sockopsBytes []byte
