{
 "title": "Sidecar Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load1" },
    { "expr": "node_load5", "legendFormat": "load5" },
    { "expr": "node_load15", "legendFormat": "load15" }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_free_bytes) # TODO: select mountpoint!"
    }
   ]
  },
  {
   "title": "Free Memory Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Cached_bytes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Container CPU Usage in Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(cpu) (irate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=\"sidecar-demo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Container Memory Usage in Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_io_kubernetes_pod_name=\"sidecar-demo\"}"
    }
   ]
  },
  {
   "title": "Average Pod Network Tx Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{name=~\".*sidecar-demo.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Average Pod Network Rx Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=~\".*sidecar-demo.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Average Pod Filesystem Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=~\".*sidecar.*\"}"
    }
   ]
  },
  {
   "title": "Average Pod Filesystem Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_writes_bytes_total{name=~\".*sidecar.*\"}"
    }
   ]
  },
  {
   "title": "Sidecar Process Forward Delay",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max without(pid) (sidecar_process_request_duration{podName=\"sidecar-demo\"}) < 5000000"
    }
   ]
  },
  {
   "title": "Establishing Connection Delay Between Sidecar and Service Container",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max without(pid) (sidecar_to_service_container_duration{podName=\"sidecar-demo\"}) < 1200000"
    }
   ]
  },
  {
   "title": "Long Connection Hits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "irate(long_connection_counter{podName=\"sidecar-demo\"}[5m])"
    }
   ]
  }
 ]
}