{
 "title": "123123",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "mmio_delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"DELAY(us)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "irq_delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"DELAY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vcpu_load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"MAX_TIME\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"min_time\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"max_time\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"total_time\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_exit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"MAX_TIME\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"MIN_TIME\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"TOTAL_TIME\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}