{
 "title": "cpu_watcher_vis",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "schedule_delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"avg_delay/us\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"max_delay/us\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bpf_metrics{bpf_out_data=\"min_delay/μs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "irqTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"irqTime/us\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "preempt_delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"duration_ns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "procs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"proc/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"sys/ms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "softirqTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"softirq/us\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "utime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"utime/ms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"idle/ms\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kthread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"kthread/us\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cswch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"cswch/s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sys_delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "bpf_metrics{bpf_out_data=\"delay/ms\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}