scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus_ip_port']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway_ip_port']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter_ip_port']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: [ 'cadvisor_ip_port' ]
  - job_name: 'sidecar_exporter'
    static_configs:
      - targets: [ 'sidecar_exporter_ip_port' ]
