{
 "title": "DNS Cache",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dnscache_loss", "legendFormat": "loss" }
   ]
  },
  {
   "title": "Reply Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dnscache_dns_request_duration_milliseconds_bucket[15s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dnscache_dns_request_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(dnscache_dns_request_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(dnscache_cache_hit_total{instance=~\".*\"}[1m]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(rate(dnscache_cache_miss_total{instance=~\".*\"}[1m]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "dnscache_cache_size" }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(dnscache_matched_dns_queries_total{instance=~\".*\"}[1m]))",
     "legendFormat": "matched"
    },
    {
     "expr": "sum(rate(dnscache_unmatched_dns_queries_total{instance=~\".*\"}[1m]))",
     "legendFormat": "unmatched"
    }
   ]
  }
 ]
}