name: net_manager

on:
  push:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/net_manager/**'
      - '.github/workflows/net_manager.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/net_manager/**'
      - '.github/workflows/net_manager.yml'

permissions:
  contents: write

jobs:
  net_manager_build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies and Init Env
        run: |
          sudo apt update
          sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386 linux-headers-$(uname -r) linux-tools-common linux-tools-generic
          sudo git submodule update --init --recursive

       
      - name: Build and Run
        run: |
          cd eBPF_Supermarket/Network_Subsystem/net_manager/
          ip a
          sudo ./configure
          sudo make
          # run
          cd net_manager
          sudo timeout -s SIGINT 5 ./xdp_loader -d ens33 -S || if [[ $? != 124 && $? != 0 ]];then exit $?;fi
          sudo ./xdp_loader -d eth0 -S
          sudo xdp-loader unload ens33 --all
  
       
         
