name: eBPF_proc_image

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/eBPF_proc_image/**'
      - '.github/workflows/eBPF_proc_image.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/eBPF_proc_image/**'
      - '.github/workflows/eBPF_proc_image.yml'

jobs:
  proc_image-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install clang libelf1 libelf-dev zlib1g-dev
          sudo apt install libbpf-dev
          sudo apt install linux-tools-5.19.0-46-generic	
          sudo apt install linux-cloud-tools-5.19.0-46-generic

      - name: Run proc_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          sudo make proc_image
          sudo ./proc_image -t 1

      - name: Run proc_offcpu_time
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/proc_offcpu_time
          sudo make
          sudo ./proc_offcpu_time -t 1

      - name: Run mutex_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          sudo make mutex_image
          sudo ./mutex_image -t 1

      - name: Run mutex_test1
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/test
          sudo make
          sudo insmod mutex_test1.ko