name: XDP

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/XDP_Res-Application/**'
      - '.github/workflows/ebpf_xdp.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/XDP_Res-Application/**'
      - '.github/workflows/ebpf_xdp.yml'
      
  pull_request_review:
  workflow_dispatch:

jobs:
  bcc-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get install bpfcc-tools linux-headers-$(uname -r)
         
      - name: Run xdp_filter
        run: |
          cd eBPF_Supermarket/XDP_Res-Application/
          sudo python3 src/xdp_filter/filter.py -t 5 -i lo -m 0

      - name: Run xdp_fast_forward
        run: |
          cd eBPF_Supermarket/XDP_Res-Application/
          sudo python3 src/xdp_fast_forward/forward.py -t 5 -i lo -m 0
