name: Test eBPF hub Projects

on:
  push:
    branches:
      - "*"
    paths:
      - 'eBPF_Hub/**'
      - 'lib/**'
      - '.github/workflows/eBPF_hub.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Hub/**'
      - 'lib/**'
      - '.github/workflows/eBPF_hub.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# In that case do the job 'make_and_deploy_doxygen'
jobs:
  ebpf-project-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get submodule
        run:  git submodule update --init --recursive
      - name: install deps
        run: |
             sudo make -C lib/build_hub install-deps
      - name: build compile set
        run:  |
              make -C lib/build_hub clone_and_install_deps
              make -C lib/build_hub test

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./eBPF_Hub
          destination: ./_site
