name: eBPF_FUSE_read

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/eBPF_FUSE/Filesystem_Subsystem/fast_fuse/**'
      - '.github/workflows/ebpf_FUSE_read.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/eBPF_FUSE/eBPF_FUSE_read/fast_fuse/**'
      - '.github/workflows/ebpf_FUSE_read.yml'
  
jobs:
  FUSE_read-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run fusedemo
        run: |
          cd eBPF_Supermarket/Filesystem_Subsystem/fast_fuse/fusedemo/
          sudo apt install fuse libfuse-dev meson ninja wget git
          git clone https://github.com/libfuse/libfuse/releases/tag/fuse-3.16.2/fuse-3.16.2.tar.gz
          tar -zxvf fuse-3.16.2.tar.gz
          mv fuse-3.16.2.tar.gz libfuse
          cd libfuse
          make
          cd ./example/
          mkdir ./yourdir
          ./fusedemo ./yourdir
          df -T ./yourdir
