name: Go

on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]
jobs:
   build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
   
    - name: Start minikube
      id: minikube
      uses: medyagh/setup-minikube@master

    - name: pod start
      run: |
        kubectl cluster-info
        kubectl create namespace wyw
        kubectl create -f eBPF_Supermarket/cilium_ebpf_probe/k8s_yaml/http_server_pod.yaml
        test_pod() {
                while [[ $(kubectl get pods -n $1 -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]
                  do 
                    echo "waiting for pod"
                    sleep 5
                    kubectl get pods -owide -A; 
                    kubectl describe pod httpserver -n wyw
                  done
                return 0
              }
        test_pod wyw
        echo "httpserver is done"
