name: Pod Monitor

on:
  push:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/cilium_ebpf_probe/**'
      - '.github/workflows/monitor_pod.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/cilium_ebpf_probe/**'
      - '.github/workflows/monitor_pod.yml'

jobs:
   build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
   
    - name: Start minikube
      id: minikube
      uses: medyagh/setup-minikube@master

    - name: pod start
      run: |
        kubectl create namespace wyw
        kubectl create -f eBPF_Supermarket/cilium_ebpf_probe/k8s_yaml/http_server_pod.yaml
        kubectl create -f eBPF_Supermarket/cilium_ebpf_probe/k8s_yaml/g_server_pod.yaml
        test_pod() {
                while [[ $(kubectl get pods -n $1 -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True True" ]]
                  do 
                    echo "waiting for pod"
                    sleep 5
                    kubectl get pods -n $1; 
                  done
                return 0
              }
        test_pod wyw
        echo "server pods is done"
        
    - name: build BCC
      run: |
          sudo apt install -y bison build-essential cmake flex git libclang-12-dev libedit-dev \
          libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev libelf-dev libfl-dev python3-distutils
          git clone --depth 1 --branch v0.24.0 https://github.com/iovisor/bcc.git
          mkdir bcc/build; cd bcc/build
          cmake ..
          make
          sudo make install
          cmake -DPYTHON_CMD=python3 .. # build python3 binding
          pushd src/python/
          make
          sudo make install
          popd
          
    - name: build main
      run: |
        cd eBPF_Supermarket/cilium_ebpf_probe
        go build main.go
