name: net_manager

on:
  push:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/net_manager/**'
      - '.github/workflows/net_manager.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/net_manager/**'
      - '.github/workflows/net_manager.yml'

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-23.10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies and Init Env
        run: |
          sudo apt update
          sudo apt install clang llvm libelf-dev libpcap-dev build-essential linux-headers-$(uname -r) linux-tools-common linux-tools-generic libc6-dev-i386 libxdp-dev xdp-tools
          sudo git submodule update --init --recursive

       
      - name: Build and Run
        run: |
          cd eBPF_Supermarket/Network_Subsystem/net_manager/
          ./configure
          make
          # run
          cd eBPF_Supermarket/Network_Subsystem/net_manager/xmac_mac
          sudo ./xdp_loader -d ens33 -S
          sudo ./xacladm load ens33 ./conf.d/mac_load.conf
  
       
         
