name: net_libbpf

on:
  push:
    branches:
      - "*"
    paths: 
      - '.github/workflows/net_libbpf.yml'
      - 'eBPF_Supermarket/Network_Subsystem/delay_analysis/libbpf_version/**'
      - 'eBPF_Supermarket/Network_Subsystem/tcp_win/**'
      - 'eBPF_Supermarket/Network_Subsystem/tcp_backlog/**'
      
  pull_request:
    branches:
      - "*"
    paths:
      - '.github/workflows/net_libbpf.yml'
      - 'eBPF_Supermarket/Network_Subsystem/delay_analysis/libbpf_version/**'
      - 'eBPF_Supermarket/Network_Subsystem/tcp_win/**'
      - 'eBPF_Supermarket/Network_Subsystem/tcp_backlog/**'
    
jobs:
  libbpf-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and Init Env
        run: |
          sudo apt install libbpf-dev clang llvm libelf-dev libpcap-dev gcc-multilib build-essential
          git submodule update --init --recursive

      - name: Build and Run
        run: |
          pushd ./
          cd eBPF_Supermarket/Network_Subsystem/delay_analysis/libbpf_version/
          make delay_analysis
          sudo ./delay_analysis -c 5
          popd
          
          pushd ./
          cd eBPF_Supermarket/Network_Subsystem/tcp_win/
          make tcp_win
          sudo ./tcp_win -c 5
          popd
          
          pushd ./
          cd eBPF_Supermarket/Network_Subsystem/tcp_backlog/
          make tcp_backlog
          sudo ./tcp_backlog &
          sudo tail /sys/kernel/debug/tracing/trace
          popd
